### ISSUE TITLE
Demo & More information

### ISSUE THREAD

**Issue by ezzabuzaid** [renatorib/github-blog#1]
Hello,

I'm trying to use your library but still can't understand how I will launch the UI.

It would be good to include a demo in the docs so anyone can quickly see what the library offers directly.

Thank you for your effort.

**Comment by renatorib** [comment]
Hey @ezzabuzaid this lib just offer the API so you can build your application wherever you want. Don't have any UI on it.
BUT I have plans (already started) to create an nextjs starter template so you can create a blog with minimum effort.
