### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Nishchit14** [renatorib/github-blog#6]
This is a great utility. Is there any live demo/examples to see the result?

**Comment by renatorib** [comment]
Hello @Nishchit14 I use this lib in my personal blog https://rena.to

You can see the issues/posts in my repo https://github.com/renatorib/posts (you can also comment but I've not implemented it yet to appear comments in my posts) 

Unfortunately my blog repo source is private, so you can't see the implementation. But it's really simple. Just a few getPost and getPosts calls, the rest is implementation details.
